defaults:
  - model: dnn
  - optimizer: AdamW
  - lr_scheduler: ExponentialLR
  - trainer: gpu
  - loss: MSE
  - _self_

_target_: superconduct_tc_reg.pipeline.dnn.DNNPipeline
_partial_: True

target: ${target}

weights_init:
  seed: ${seed}

data_loader:
  seed: ${seed}
  num_workers: 0
  drop_last: False
  pin_memory: False
  persistent_workers: False

trainer:
  deterministic: False
  max_epochs: 60
  batch_size: 4096

warmup:
  epochs: 5
  lr: 0.0005

do_checkpointing: False
matmul_precision: "high"