out_file_name: train-ho-hd_5-sc_std-cfs.csv

steps:
  outliers:
    _target_: superconduct_tc_reg.data.process.remove_outliers
    _partial_: True
    outliers: [20573]
  duplicates:
    _target_: superconduct_tc_reg.data.process.remove_duplicates
    _partial_: True
    threshold: 5
    col_target: ${target}
  scale:
    _target_: sklearn.preprocessing.StandardScaler
  CFS:
    _target_: superconduct_tc_reg.data.process.remove_highly_correlated_features
    _partial_: True
    threshold: 0.99
    method: "pearson"