defaults:
  - tracking: mlflow_dagshub
  - _self_

data_processor_artifact:
  name: data_processor.joblib
  path: data_processing

source_model_name: superconduct-gbdt:onnx
path_to_model: "models/${source_model_name}"
run_id: "???"
model_name: "${source_model_name}:ete"