_target_: lightning.pytorch.loggers.MLFlowLogger
experiment_name: "debug"
tracking_uri: "/home/yparomau/PycharmProjects/superconduct-tc-reg/mlflow_tracking"
artifact_location: "/home/yparomau/PycharmProjects/superconduct-tc-reg/mlflow_artifacts"
synchronous: True