_target_: lightning.pytorch.loggers.MLFlowLogger
_partial_: True
experiment_name: "isml/superconduct-tc-reg/debug"
tracking_uri: "http://172.26.122.53:5000/"
artifact_location: null
synchronous: True
log_model: False