NDVIAVG:
  AKE:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 497.68
      min: 18.16
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 551.17
      min: 59.07
  BS:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 99.5
      min: 2.77
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 99.6
      min: 5.24
  C_N:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 38.94
      min: 11.36
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 36.0
      min: 14.3636363636364
  pH_KCl:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 6.12
      min: 2.61
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 5.91
      min: 2.42
S2:
  AKE:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 497.68
      min: 18.16
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 551.17
      min: 59.07
  BS:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 99.5
      min: 2.77
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 99.6
      min: 5.24
  C_N:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 38.94
      min: 11.36
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 36.0
      min: 14.3636363636364
  pH_KCl:
    ah:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 6.12
      min: 2.61
    oh:
      _target_: soil_analysis.nn.scaler.MinMaxScaler
      max: 5.91
      min: 2.42
